language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- chmod +x ./setup.py
- python setup.py test
- python setup.py build
- python setup.py sdist
- python setup.py bdist
- python setup.py install
- coverage run --source=src --omit="*/test_*,*__init__*" ./setup.py test
after_success:
- coveralls --verbose